

import React from 'react';

const ScheduleCard = ({ schedule, onEdit, onDelete, onActivate }) => {
  const formatDateTime = (dateTimeString) => {
    if (!dateTimeString) return 'N/A';
    
    try {
      return new Date(dateTimeString).toLocaleString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
    } catch (error) {
      console.error('Error formatting date:', error);
      return 'Invalid Date';
    }
  };

  const getStatusBadge = (isActive) => {
    if (isActive) {
      return (
        <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-green-100 text-green-800">
          <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          Active
        </span>
      );
    }
    return (
      <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-gray-100 text-gray-800">
        <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        Inactive
      </span>
    );
  };

  // Safe data accessors for your API response structure
  const getDepartmentName = () => {
    return schedule.department_name || 'Unknown Department';
  };

  const getAcademicSessionName = () => {
    return schedule.academic_session_name || 'Unknown Session';
  };

 // In your ScheduleCard component, update the getGeneratedByName function:

const getGeneratedByName = () => {
  // Priority 1: Use generated_by_display_name if available (from alternative serializer)
  if (schedule.generated_by_display_name && schedule.generated_by_display_name.trim() !== '') {
    return schedule.generated_by_display_name;
  }

  // Priority 2: Use generated_by_user_type to check if chairperson
  if (schedule.generated_by_user_type && ['admin', 'chairperson'].includes(schedule.generated_by_user_type.toLowerCase())) {
    return 'Chairperson';
  }

  // Priority 3: Use generated_by_name from API if available
  if (schedule.generated_by_name && schedule.generated_by_name.trim() !== '') {
    return schedule.generated_by_name;
  }

  // Priority 4: Use generated_by_username if available
  if (schedule.generated_by_username && schedule.generated_by_username.trim() !== '') {
    return schedule.generated_by_username;
  }

  // Priority 5: If generated_by is an object with user data
  if (schedule.generated_by && typeof schedule.generated_by === 'object') {
    const user = schedule.generated_by;
    return user.username || user.email?.split('@')[0] || 'User';
  }

  // Priority 6: If generated_by is just an ID
  if (schedule.generated_by) {
    return `User ${schedule.generated_by}`;
  }

  return 'Unknown User';
};

// Add this function to check if it's a chairperson schedule
const isChairpersonSchedule = () => {
  return schedule.is_chairperson_schedule || 
         (schedule.generated_by_user_type && ['admin', 'chairperson'].includes(schedule.generated_by_user_type.toLowerCase()));
}; 

  // Debug: Check what data we're receiving
  console.log('🔍 Schedule data for debugging:', {
    id: schedule.id,
    name: schedule.name,
    generated_by: schedule.generated_by,
    generated_by_name: schedule.generated_by_name,
    has_generated_by_name: !!schedule.generated_by_name,
    generated_by_name_value: schedule.generated_by_name
  });

  return (
    <div className={`border rounded-lg p-6 ${schedule.is_active ? 'border-green-300 bg-green-50' : 'border-gray-200 bg-white'} transition-all duration-200 hover:shadow-md`}>
      <div className="flex justify-between items-start mb-4">
        <div className="flex-1">
          <div className="flex items-center space-x-3 mb-2">
            <h3 className="text-xl font-semibold text-gray-900">
              {schedule.name}
            </h3>
            {getStatusBadge(schedule.is_active)}
          </div>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm text-gray-600 mb-4">
            <div>
              <span className="font-medium text-gray-700">Department:</span>{' '}
              {getDepartmentName()}
            </div>
            <div>
              <span className="font-medium text-gray-700">Academic Session:</span>{' '}
              {getAcademicSessionName()}
            </div>
            <div>
              <span className="font-medium text-gray-700">Generated By:</span>{' '}
              <span className={getGeneratedByName().startsWith('User ') ? 'text-orange-500' : ''}>
                {getGeneratedByName()}
              </span>
            </div>
            <div>
              <span className="font-medium text-gray-700">Generated At:</span>{' '}
              {formatDateTime(schedule.generated_at)}
            </div>
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-2 justify-between items-center pt-4 border-t border-gray-200">
        <div className="flex flex-wrap gap-2">
          {!schedule.is_active && (
            <button
              onClick={() => onActivate(schedule.id)}
              className="inline-flex items-center px-3 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
            >
              <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              Activate
            </button>
          )}
          
          <button
            onClick={() => onEdit(schedule)}
            className="inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
            Edit
          </button>
        </div>

        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => onDelete(schedule.id)}
            className="inline-flex items-center px-3 py-2 border border-transparent text-sm font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
          >
            <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
            Delete
          </button>
        </div>
      </div>

      {/* Active Schedule Notice */}
      {schedule.is_active && (
        <div className="mt-4 p-3 bg-green-100 border border-green-200 rounded-md">
          <div className="flex items-center">
            <svg className="w-5 h-5 text-green-600 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span className="text-sm text-green-800 font-medium">
              This is the currently active schedule for {getDepartmentName()}
            </span>
          </div>
        </div>
      )}
    </div>
  );
};

export default ScheduleCard;


















