# Generated by Django 5.2.6 on 2025-11-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_date'], 'verbose_name': 'Academic Session', 'verbose_name_plural': 'Academic Sessions'},
        ),
        migrations.AlterModelOptions(
            name='classsection',
            options={'ordering': ['academic_session', 'semester', 'name'], 'verbose_name': 'Class Section', 'verbose_name_plural': 'Class Sections'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseoffering',
            options={'verbose_name': 'Course Offering', 'verbose_name_plural': 'Course Offerings'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='generatedschedule',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Generated Schedule', 'verbose_name_plural': 'Generated Schedules'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['code'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['time_slot__day', 'time_slot__start_time'], 'verbose_name': 'Schedule Entry', 'verbose_name_plural': 'Schedule Entries'},
        ),
        migrations.AlterModelOptions(
            name='scheduleexception',
            options={'ordering': ['exception_date'], 'verbose_name': 'Schedule Exception', 'verbose_name_plural': 'Schedule Exceptions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_number'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['employee_id'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'verbose_name': 'Teacher Assignment', 'verbose_name_plural': 'Teacher Assignments'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='department',
            field=models.ForeignKey(help_text='The department running or managing this session.', on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this the current active session?'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='name',
            field=models.CharField(help_text='Friendly name (e.g., BSCS 3A).', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Unique course code (e.g., CS-101, MATH-205).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(help_text='The department that offers this course.', on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='is_core',
            field=models.BooleanField(default=True, help_text='Is this a core/mandatory course for the section?'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Unique short code for the department (e.g., CSE, BUS).', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='generatedschedule',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this the schedule currently being used by the institution?'),
        ),
        migrations.AlterField(
            model_name='generatedschedule',
            name='name',
            field=models.CharField(help_text="e.g., 'Draft 1 - Finalized'", max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(help_text='Unique code for the program (e.g., BSCS, MSEE).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='total_credits',
            field=models.IntegerField(help_text='Total credit hours required for the program.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(help_text='The department primarily responsible for this room.', on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='academic_session',
            field=models.ForeignKey(blank=True, help_text='The session this schedule block belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.academicsession'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='class_section',
            field=models.ForeignKey(help_text='The student group attending this class.', on_delete=django.db.models.deletion.CASCADE, to='myapp.classsection'),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='schedule',
            field=models.ForeignKey(help_text='The original schedule entry being overridden.', on_delete=django.db.models.deletion.CASCADE, to='myapp.schedule'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(help_text='The current academic section the student is enrolled in.', on_delete=django.db.models.deletion.CASCADE, to='myapp.classsection'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(help_text='Unique student identification number.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_lectures_per_week',
            field=models.IntegerField(default=20, help_text='Maximum number of classes a teacher can be assigned weekly.'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='is_responsible_teacher',
            field=models.BooleanField(default=False, help_text='Is this teacher the primary coordinator for this section/course combination?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot_name',
            field=models.CharField(help_text="A friendly name for the slot (e.g., 'Morning Slot 1').", max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department affiliation for the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
    ]
